language: android
android:
  components:
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository
script:
  - ./gradlew ktlint app:testDebugUnitTest data:testDebugUnitTest domain:testDebugUnitTest
before_install:
  - chmod +x gradlew
branches:
  only:
    - gh-pages
    - /.*/