language: android
android:
        components:
                - platform-tools
                - build-tools-28.0.3
                - android-28
		- android-21
                - extra-android-m2repository
script:
        - ./gradlew build
	- ./gradlew lint ktlintCheck checkstyle
before_install:
        - chmod +x gradlew